In [38]:
import torch
import torch.nn as nn
import torch.functional as F   
import numpy as np     

In [7]:
with open('mini_shakespeare.txt') as file:
    file_content = file.read()

alphabet = sorted(list(set(file_content)))
stoi = {char: i for i, char in enumerate(alphabet)}
itos = {i: char for i, char in enumerate(alphabet)}
encode = lambda x: [stoi[char] for char in x]
decode = lambda x: [itos[encoded_char] for encoded_char in x]
data = encode(file_content)
cutoff = int(len(data)*0.9)
train = data[:cutoff]
val = data[cutoff:]


In [40]:
vocab_size = len(alphabet)
block_size = 8
batch_size = 4
embed_dim = 1
head_size = 32

In [ ]:
class AttentionHead(nn.Module):
    def __init__(self):
        super().__init__()
        self.queries = nn.Linear(embed_dim, head_size, bias = False)
        self.keys = nn.Linear(embed_dim, head_size, bias = False)
        self.values = nn.Linear(embed_dim, head_size, bias = False)
    def forward(self, x):
        q = self.queries(x) ## (B, T, 32)
        k = self.keys(x).transpose(1,2) ## (B, 32, T)
        trans = q @ k /np.sqrt(embed_dim) ## (B, T, T)  
        trans[0, 0,0] =0
        softmax = torch.softmax(trans, dim=2)
        return q, k
    
m = AttentionHead()
x = m(torch.ones((1,3,1), dtype=torch.float))


tensor([[[0.0000, 1.4297, 1.4297],
         [1.4297, 1.4297, 1.4297],
         [1.4297, 1.4297, 1.4297]]], grad_fn=<CopySlices>)
tensor([[[0.1069, 0.4466, 0.4466],
         [0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333]]], grad_fn=<SoftmaxBackward0>)


In [24]:
torch.zeros((1,3), dtype=torch.float)

tensor([[0., 0., 0.]])